(() => {
  'use strict';
  const API_BASE = '/api/v1/monitor';
  const MANUFACTURERS = ['Samsung SDI', 'LG Energy Solution', 'SK On'];
  const REGIONS = ['Jeonnam', 'Jeonbuk', 'Gyeonggi', 'Gyeongnam', 'Daejeon'];
  const AREAS = ['Power room A', 'Power room B', 'Outdoor cabinet', 'Test zone', 'ESS room'];
  const state = { page: 'dashboard', sites: [], selectedSiteId: null, level: 'site', bank: 1, rack: 1, string: 1, module: 1, treeOpen: true, filters: { q: '', manufacturer: '', region: '', area: '', status: '' } };
  const $ = (id) => document.getElementById(id);
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num = (v, d=0) => Number.isFinite(Number(v)) ? Number(v) : d;
  const pad2 = (v) => String(v).padStart(2, '0');
  function fmtTime(value){ if(!value) return '-'; return String(value).replace('T',' ').replace(/\.\d+$/,'').slice(0,19); }
  function score(value){ const x=num(value,0); return Math.round(Math.max(0, Math.min(100, x <= 1 ? x*100 : x))); }
  function statusFromScore(v){ const s=score(v); if(s>=80) return 'abnormal'; if(s>=50) return 'warning'; return 'normal'; }
  function statusClass(v){ const k=String(v||'').toLowerCase(); if(k==='abnormal'||k==='danger') return 'abnormal'; if(k==='warning'||k==='caution') return 'warning'; if(k==='offline') return 'offline'; return 'normal'; }
  function statusLabel(v){ const k=statusClass(v); return k==='abnormal'?'비정상':k==='warning'?'주의':k==='offline'?'오프라인':'정상'; }
  function dot(v){ const k=statusClass(v); return `<i class="status-dot ${k}" title="${statusLabel(k)}"></i>`; }
  function derive(site){
    const no = num(site.site_no || String(site.site_id || '').match(/\d+/)?.[0], 0);
    const sc = score(site.latest_score ?? site.max_score ?? 0);
    const st = site.status ? statusClass(site.status) : statusFromScore(sc);
    const rackCount = Math.max(1,num(site.rack_count,3));
    const stringCount = Math.max(1,num(site.string_count,2));
    const moduleCount = Math.max(1,num(site.module_count,12));
    return {...site, site_id:site.site_id||`SITE-${no}`, site_no:no||site.site_no||'-', site_name:site.site_name||`ESS Site ${no||''}`.trim(), bms_id:site.bms_id||'BMS-UNKNOWN', manufacturer:(site.manufacturer&&site.manufacturer!=='-')?site.manufacturer:MANUFACTURERS[no%MANUFACTURERS.length], region:(site.region&&site.region!=='-')?site.region:REGIONS[no%REGIONS.length], install_area:(site.install_area&&site.install_area!=='-')?site.install_area:AREAS[no%AREAS.length], installed_at:fmtTime(site.installed_at).slice(0,10), last_analysis_time:fmtTime(site.last_analysis_time), latest_score:sc, average_score:Math.round(num(site.average_score, Math.max(20,sc-18))), status:st, status_text:statusLabel(st), bank_count:Math.max(1,num(site.bank_count,1)), rack_count:rackCount, string_count:stringCount, module_count:moduleCount, cell_count:Math.max(20,num(site.cell_count,moduleCount*20)), risk_location:site.risk_location||'Bank 01 > Rack 01 > String 01 > Module 01', score_row_count:num(site.score_row_count,moduleCount)};
  }
  function fallbackSites(){ return [
    {site_id:'SITE-9001__BMS-DEMO-BMS-01',site_no:9001,site_name:'ESS Site 9001',bms_id:'DEMO-BMS-01',latest_score:97,status:'abnormal',rack_count:3,string_count:2,module_count:12,cell_count:240,last_analysis_time:'2026-08-05 09:07:38'},
    {site_id:'SITE-9001__BMS-FAKE-BMS-9001',site_no:9001,site_name:'ESS Site 9001',bms_id:'FAKE-BMS-9001',latest_score:77,status:'warning',rack_count:2,string_count:1,module_count:12,cell_count:240,last_analysis_time:'2026-08-05 10:26:56'},
    {site_id:'SITE-9002',site_no:9002,site_name:'ESS Site 9002',bms_id:'BMS-9002',latest_score:88,status:'abnormal',rack_count:4,string_count:2,module_count:16,cell_count:320,last_analysis_time:'2026-08-05 09:07:38'},
    {site_id:'SITE-9003',site_no:9003,site_name:'ESS Site 9003',bms_id:'BMS-9003',latest_score:45,status:'normal',rack_count:2,string_count:2,module_count:8,cell_count:160,last_analysis_time:'2026-08-05 09:07:38'}].map(derive); }
  async function getJson(url){ const r=await fetch(url,{cache:'no-store'}); if(!r.ok) throw new Error(url); return r.json(); }
  async function loadData(){ try{ const data=await getJson(`${API_BASE}/sites`); const arr=Array.isArray(data)?data:(data.sites||data.items||[]); state.sites=(arr.length?arr:fallbackSites()).map(derive).sort((a,b)=>b.latest_score-a.latest_score); }catch(e){ console.warn('[monitor] fallback sites',e); state.sites=fallbackSites(); } if(!state.selectedSiteId&&state.sites.length) state.selectedSiteId=state.sites[0].site_id; }
  function currentSite(){ return state.sites.find(s=>s.site_id===state.selectedSiteId)||state.sites[0]||derive({}); }
  function childScore(site,level,i){ return Math.max(0, Math.min(100, site.latest_score - (i-1)*4 + (level==='module'?(i%3)*3:0))); }
  function childStatus(site,level,i){ return statusFromScore(childScore(site,level,i)); }
  function countStatus(){ const c={normal:0,warning:0,abnormal:0,offline:0}; state.sites.forEach(s=>c[statusClass(s.status)]++); return c; }
  function shell(main){ const site=currentSite(); const now=new Date().toISOString().replace('T',' ').slice(0,19); return `<div class="monitor-shell"><aside class="monitor-sidebar"><div class="brand"><b>KESCO</b><span>Monitoring</span></div><nav class="side-nav">${nav('dashboard','대시보드','⌂')}${nav('sites','사이트 목록','☷')}${nav('detail','사이트 상세','▣')}${nav('history','실행 이력','↻')}${nav('settings','설정','⚙')}</nav>${state.page==='detail'?renderTree(site):''}<div class="side-footer"><span>시스템 버전</span><b>v2.7.0</b></div></aside><section class="monitor-main"><header class="topbar"><span class="top-pill">◷ ${now}</span><span class="top-pill good">● API 서버 정상</span><span class="top-pill good">▦ DB 정상</span><span class="top-pill">◷ 마지막 분석 시각 : ${esc(site.last_analysis_time||'-')}</span><span class="top-user">관리자</span></header><main class="page-wrap">${main}</main></section></div>`; }
  function nav(page,label,icon){ return `<button class="nav-item ${state.page===page?'active':''}" onclick="Monitor.goPage('${page}')"><span>${icon}</span>${label}</button>`; }
  function renderTree(site){ if(!state.treeOpen) return `<div class="tree-box"><div class="tree-head"><b>계층 구조 탐색</b><button onclick="Monitor.resetTree()">↻</button></div><button class="tree-row ${state.level==='site'?'active':''}" onclick="Monitor.selectLevel('site')">${dot(site.status)}<span>${esc(site.site_name)}</span><b>${site.latest_score}</b></button></div>`; const rackCount=site.rack_count; const stringPerRack=Math.max(1,Math.ceil(site.string_count/rackCount)); const modulePerString=Math.max(1,Math.ceil(site.module_count/Math.max(1,rackCount*stringPerRack))); let h=`<div class="tree-box"><div class="tree-head"><b>계층 구조 탐색</b><button title="계층 접기" onclick="Monitor.resetTree()">↻</button></div>`; h+=`<button class="tree-row ${state.level==='site'?'active':''}" onclick="Monitor.selectLevel('site')">${dot(site.status)}<span>${esc(site.site_name)}</span><b>${site.latest_score}</b></button>`; for(let b=1;b<=site.bank_count;b++){ h+=`<button class="tree-row ${state.level==='bank'&&state.bank===b?'active':''}" onclick="Monitor.selectLevel('bank',${b})">${dot(childStatus(site,'bank',b))}<em>B</em><span>Bank ${pad2(b)}</span></button>`; for(let r=1;r<=rackCount;r++){ h+=`<button class="tree-row child ${state.level==='rack'&&state.rack===r?'active':''}" onclick="Monitor.selectLevel('rack',${b},${r})">${dot(childStatus(site,'rack',r))}<em>R</em><span>Rack ${pad2(r)}</span></button>`; if(state.level!=='site'){ for(let st=1;st<=stringPerRack;st++){ h+=`<button class="tree-row child2 ${state.level==='string'&&state.rack===r&&state.string===st?'active':''}" onclick="Monitor.selectLevel('string',${b},${r},${st})">${dot(childStatus(site,'string',st+r))}<em>S</em><span>String ${pad2(st)}</span></button>`; if(state.rack===r&&state.string===st){ for(let m=1;m<=modulePerString;m++){ const moduleNo=(r-1)*stringPerRack*modulePerString+(st-1)*modulePerString+m; h+=`<button class="tree-row child3 ${state.level==='module'&&state.module===moduleNo?'active':''}" onclick="Monitor.selectLevel('module',${b},${r},${st},${moduleNo})">${dot(childStatus(site,'module',moduleNo))}<em>M</em><span>Module ${pad2(moduleNo)}</span></button>`; } } } } } } return h+`<div class="legend"><span>${dot('normal')}정상</span><span>${dot('warning')}주의</span><span>${dot('abnormal')}비정상</span><span>${dot('offline')}오프라인</span></div></div>`; }
  function renderDashboard(){ const c=countStatus(); const top=[...state.sites].sort((a,b)=>b.latest_score-a.latest_score).slice(0,3); return shell(`<section class="page-title"><h1>대시보드</h1><p>전체 사이트 현황과 우선 점검 대상을 확인합니다.</p></section><div class="summary-grid"><article class="metric"><span>전체 사이트</span><b>${state.sites.length}</b></article><article class="metric good"><span>정상</span><b>${c.normal}</b></article><article class="metric warn"><span>주의</span><b>${c.warning}</b></article><article class="metric bad"><span>비정상</span><b>${c.abnormal}</b></article></div><div class="dashboard-grid"><section class="panel"><h2>우선 점검 대상 TOP 3</h2>${top.map((s,i)=>priorityRow(s,i+1)).join('')}</section><section class="panel"><h2>상태 요약</h2>${bar('정상',c.normal,state.sites.length,'good')}${bar('주의',c.warning,state.sites.length,'warn')}${bar('비정상',c.abnormal,state.sites.length,'bad')}</section></div>`); }
  function priorityRow(s,i){ return `<button class="priority-row" onclick="Monitor.openDetail('${esc(s.site_id)}','site')"><b class="rank ${s.status}">${i}</b><span><strong>${esc(s.site_name)}</strong><small>${esc(s.bms_id)} · ${esc(s.region)} · ${esc(s.manufacturer)}</small></span><em class="score ${s.status}">${s.latest_score}</em></button>`; }
  function bar(label,value,total,cls){ const pct=total?Math.round(value/total*100):0; return `<div class="bar-row"><span>${label}</span><div><i class="${cls}" style="width:${pct}%"></i></div><b>${value}</b></div>`; }
  function renderSites(){ const list=filteredSites(); return shell(`<section class="page-title"><h1>사이트 목록</h1><p>사이트 현황을 검색하고 상세 화면으로 이동합니다.</p></section><section class="filter-card"><input placeholder="사이트명 또는 BMS ID 검색" value="${esc(state.filters.q)}" oninput="Monitor.setFilter('q',this.value)">${selectFilter('manufacturer','제조사',[...new Set(state.sites.map(s=>s.manufacturer))])}${selectFilter('region','지역',[...new Set(state.sites.map(s=>s.region))])}${selectFilter('area','설치구역',[...new Set(state.sites.map(s=>s.install_area))])}<select onchange="Monitor.setFilter('status',this.value)"><option value="">진단 상태</option><option value="normal" ${state.filters.status==='normal'?'selected':''}>정상</option><option value="warning" ${state.filters.status==='warning'?'selected':''}>주의</option><option value="abnormal" ${state.filters.status==='abnormal'?'selected':''}>비정상</option></select></section><section class="table-card"><table><thead><tr><th>사이트 / BMS</th><th>지역</th><th>설치구역</th><th>제조사</th><th>설치일</th><th>최신 점수</th><th>상태</th><th>최근 분석시각</th><th>상세</th></tr></thead><tbody>${list.map(siteRow).join('')}</tbody></table></section>`); }
  function selectFilter(key,label,items){ return `<select onchange="Monitor.setFilter('${key}',this.value)"><option value="">${label}</option>${items.map(x=>`<option value="${esc(x)}" ${state.filters[key]===x?'selected':''}>${esc(x)}</option>`).join('')}</select>`; }
  function filteredSites(){ const q=state.filters.q.trim().toLowerCase(); return state.sites.filter(s=>{ if(q&&!(`${s.site_name} ${s.bms_id}`.toLowerCase().includes(q)))return false; if(state.filters.manufacturer&&s.manufacturer!==state.filters.manufacturer)return false; if(state.filters.region&&s.region!==state.filters.region)return false; if(state.filters.area&&s.install_area!==state.filters.area)return false; if(state.filters.status&&s.status!==state.filters.status)return false; return true; }); }
  function siteRow(s){ return `<tr><td><strong>${esc(s.site_name)}</strong><small>${esc(s.bms_id)}</small></td><td>${esc(s.region)}</td><td>${esc(s.install_area)}</td><td>${esc(s.manufacturer)}</td><td>${esc(s.installed_at)}</td><td><b class="score ${s.status}">${s.latest_score}</b></td><td><span class="badge ${s.status}">${statusLabel(s.status)}</span></td><td>${esc(s.last_analysis_time)}</td><td><button class="mini-btn" onclick="Monitor.openDetail('${esc(s.site_id)}','site')">보기</button></td></tr>`; }
  function renderDetail(){ const site=currentSite(); return shell(`<section class="detail-head"><div>${breadcrumb(site)}</div><button class="outline-btn" onclick="Monitor.goPage('sites')">다른 사이트 보기</button></section><section class="detail-layout"><main class="detail-main"><article class="hero-card"><div class="site-icon">▦</div><div><h1>${esc(site.site_name)} ${state.level==='site'?'Overview':levelLabel(state.level)+' Detail'}</h1><p>${esc(site.bms_id)} · ${esc(site.region)} · ${esc(site.manufacturer)}</p></div></article><div class="level-tabs">${['site','bank','rack','string','module'].map(l=>`<button class="${state.level===l?'active':''}" onclick="Monitor.selectLevel('${l}')">${levelLabel(l)}</button>`).join('')}</div>${renderLevel(site)}</main><aside class="detail-rail">${operationAdvice(site)}${analysisSummary(site)}</aside></section>`); }
  function breadcrumb(site){ const parts=[`<button onclick="Monitor.goPage('sites')">사이트 목록</button>`,`<button onclick="Monitor.selectLevel('site')">${esc(site.site_name)}</button>`]; if(state.level!=='site')parts.push(`<button onclick="Monitor.selectLevel('bank',${state.bank})">Bank ${pad2(state.bank)}</button>`); if(['rack','string','module'].includes(state.level))parts.push(`<button onclick="Monitor.selectLevel('rack',${state.bank},${state.rack})">Rack ${pad2(state.rack)}</button>`); if(['string','module'].includes(state.level))parts.push(`<button onclick="Monitor.selectLevel('string',${state.bank},${state.rack},${state.string})">String ${pad2(state.string)}</button>`); if(state.level==='module')parts.push(`<button onclick="Monitor.selectLevel('module',${state.bank},${state.rack},${state.string},${state.module})">Module ${pad2(state.module)}</button>`); return `<nav class="breadcrumb">${parts.join('<span>›</span>')}</nav>`; }
  function levelLabel(l){ return {site:'Site',bank:'Bank',rack:'Rack',string:'String',module:'Module'}[l]||l; }
  function renderLevel(site){ if(state.level==='site') return renderSiteOverview(site); if(state.level==='bank')return renderBank(site); if(state.level==='rack')return renderRack(site); if(state.level==='string')return renderString(site); return renderModule(site); }
  function info(a,b){ return `<div class="info-card"><span>${esc(a)}</span><b>${esc(b||'-')}</b></div>`; }
  function renderSiteOverview(site){ return `<section class="panel"><h2>Site Information</h2><div class="info-grid">${info('BMS ID',site.bms_id)}${info('Region',site.region)}${info('Install Area',site.install_area)}${info('Manufacturer',site.manufacturer)}${info('Installed',site.installed_at)}${info('Status',statusLabel(site.status))}${info('Max Score',site.latest_score)}${info('Last Analysis',site.last_analysis_time)}</div></section><section class="panel"><h2>Banks in Site</h2><div class="card-grid">${Array.from({length:site.bank_count},(_,i)=>entityCard('bank',i+1,site)).join('')}</div></section>`; }
  function renderBank(site){ return `<section class="panel"><h2>Bank Summary</h2><div class="info-grid">${info('Selected Bank',`Bank ${pad2(state.bank)}`)}${info('Rack Count',site.rack_count)}${info('Max Score',site.latest_score)}${info('Status',statusLabel(site.status))}</div></section><section class="panel"><h2>Racks in Bank</h2><div class="card-grid">${Array.from({length:site.rack_count},(_,i)=>entityCard('rack',i+1,site)).join('')}</div></section>`; }
  function renderRack(site){ const cnt=Math.max(1,Math.ceil(site.string_count/site.rack_count)); return `<section class="panel"><h2>Rack Summary</h2><div class="info-grid">${info('Selected Rack',`Rack ${pad2(state.rack)}`)}${info('String Count',cnt)}${info('Max Score',Math.round(childScore(site,'rack',state.rack)))}${info('Status',statusLabel(childStatus(site,'rack',state.rack)))}</div></section><section class="panel"><h2>Strings in Rack</h2><div class="card-grid">${Array.from({length:cnt},(_,i)=>entityCard('string',i+1,site)).join('')}</div></section>`; }
  function renderString(site){ const sp=Math.max(1,Math.ceil(site.string_count/site.rack_count)); const cnt=Math.max(1,Math.ceil(site.module_count/Math.max(1,site.rack_count*sp))); return `<section class="panel"><h2>String Summary</h2><div class="info-grid">${info('Selected String',`String ${pad2(state.string)}`)}${info('Module Count',cnt)}${info('Max Score',Math.round(childScore(site,'string',state.string)))}${info('Status',statusLabel(childStatus(site,'string',state.string)))}</div></section><section class="panel"><h2>Modules in String</h2><div class="card-grid">${Array.from({length:cnt},(_,i)=>entityCard('module',i+1,site)).join('')}</div></section>`; }
  function renderModule(site){ const arr=[18,22,31,26,29,34,92,45,28,33,24,37,41,27,39,26,30,35,47,32]; return `<section class="panel"><h2>Module Summary</h2><div class="info-grid">${info('Selected Module',`Module ${pad2(state.module)}`)}${info('Cell Count',20)}${info('Max Cell Score',Math.max(...arr))}${info('Status',statusLabel(statusFromScore(Math.max(...arr))))}</div></section><section class="panel"><h2>Cell Status Map</h2><div class="cell-map">${arr.map((s,i)=>`<div class="cell ${statusFromScore(s)}"><span>Cell ${pad2(i+1)}</span><b>${s}</b></div>`).join('')}</div></section>`; }
  function entityCard(level,i,site){ const st=childStatus(site,level,i), sc=Math.round(childScore(site,level,i)); const action=level==='bank'?`Monitor.selectLevel('bank',${i})`:level==='rack'?`Monitor.selectLevel('rack',${state.bank},${i})`:level==='string'?`Monitor.selectLevel('string',${state.bank},${state.rack},${i})`:`Monitor.selectLevel('module',${state.bank},${state.rack},${state.string},${i})`; return `<button class="entity-card" onclick="${action}">${dot(st)}<strong>${levelLabel(level)} ${pad2(i)}</strong><small>Open ${levelLabel(level)} detail</small><b class="score ${st}">${sc}</b></button>`; }
  function operationAdvice(site){ const st=statusFromScore(site.latest_score); const title=st==='abnormal'?'즉시 점검 권고':st==='warning'?'주의 관찰 필요':'정상 운전'; const msg=st==='abnormal'?'최고 이상점수가 높습니다. 위험 위치를 우선 확인하세요.':st==='warning'?'추이 확인이 필요합니다. 다음 분석 결과를 비교하세요.':'현재 점수는 정상 범위입니다.'; return `<section class="panel rail-card"><h2>운영 권고</h2><div class="advice ${st}"><b>${title}</b><p>${msg}</p><small>${esc(site.risk_location)}</small></div></section>`; }
  function analysisSummary(site){ return `<section class="panel rail-card"><h2>분석 요약</h2><div class="rail-list"><p><span>최근 분석</span><b>${esc(site.last_analysis_time)}</b></p><p><span>최고 점수</span><b>${site.latest_score}</b></p><p><span>평균 점수</span><b>${site.average_score}</b></p><p><span>Score rows</span><b>${site.score_row_count}</b></p></div></section>`; }
  function renderHistory(){ return shell(`<section class="page-title"><h1>실행 이력</h1><p>파이프라인 실행 이력은 다음 단계에서 연결합니다.</p></section><section class="panel">준비 중</section>`); }
  function renderSettings(){ return shell(`<section class="page-title"><h1>설정</h1><p>화면 설정과 API 설정은 다음 단계에서 정리합니다.</p></section><section class="panel">준비 중</section>`); }
  function render(){ const root=$('app')||document.body; if(state.page==='sites') root.innerHTML=renderSites(); else if(state.page==='detail') root.innerHTML=renderDetail(); else if(state.page==='history') root.innerHTML=renderHistory(); else if(state.page==='settings') root.innerHTML=renderSettings(); else root.innerHTML=renderDashboard(); }
  window.Monitor={ goPage(page){ state.page=page; render(); }, openDetail(id,level='site'){ state.selectedSiteId=id; state.page='detail'; state.level=level; state.treeOpen=true; render(); }, selectLevel(level,bank=state.bank,rack=state.rack,string=state.string,module=state.module){ state.page='detail'; state.level=level; state.bank=bank||1; state.rack=rack||1; state.string=string||1; state.module=module||1; state.treeOpen=true; render(); }, resetTree(){ state.level='site'; state.bank=1; state.rack=1; state.string=1; state.module=1; state.treeOpen=false; render(); }, setFilter(k,v){ state.filters[k]=v; render(); } };
  document.addEventListener('DOMContentLoaded', async()=>{ await loadData(); render(); });
})();
